### ISSUE TITLE
Add a way to supply custom java options as environment variables

### ISSUE THREAD

**Issue by janhoy** [UCLALibrary/docker-cantaloupe#124]
We need to specify Cantaloupe container heap size not as a percentage but as fixed size.
We also want to pass other java-level options such as `-XX:+ExitOnOutOfMemoryError` and possibly other.

Currently we clone `run_cantaloupe.sh` and mount a custom version of that file into the container.

We'll provide a PR with a proposed extension that allows docker-image users to pass the `JAVA_OPTS` and/or `HEAP_SIZE` variables to the container to customize.

**Comment by ksclarke** [comment]
Thanks for the PR. Just to clarify, do you want to add the specific heap size in addition to the percentage? Or would you want to use the fixed heap size instead of the percentage?

@cachemeoutside Also, weren't you talking about the need for JAVA_OPTS for something else recently (I'm forgetting what it was exactly)? If so, maybe we want to split out that option from the fixed heap setting?

**Comment by janhoy** [comment]
According to docs, `-Xmx` will override the percentage if both are present, so if a user does not specify `HEAP_SIZE` then it will still use percentage. I'm also fine with just adding the `JAVA_OPTS` variable and let users populate that with `-Xmx` or whatever they need from the outside.

**Comment by ksclarke** [comment]
I'll wait to hear from @cachemeoutside what our needs are w/r/t the JAVA_OPTS. Thanks for the info on the overriding of memory settings.

**Comment by janhoy** [comment]
Here is a source about the params: https://stackoverflow.com/questions/54071798/what-is-the-difference-between-xmx-and-maxram-jvm-parameters 

You are right that if you choose to restrict memory through Docker / k8s-podspec then the percentage is preferred and a best practice. I can change the PR to skip handling og HEAP_SIZE and leave just the `${JAVA_OPTS}` (or `${CANTALOUPE_JAVA_OPTS}` perhaps to namespace it better?

**Comment by ksclarke** [comment]
Since there may be environments where someone wants to use the fixed size, I'm fine with providing that as a configuration option.

We could maybe just document that we'd recommend using the percentage in a Kubernetes environment (but, still, people are free to do what works for them). I don't think providing the option for both complicates it too much.

**Comment by ksclarke** [comment]
Oh, from your example above, I guess that is on jobs not steps, so that would just be at one place in the GA (which isn't bad). That would though prevent the forker from ever being able to run the GAs locally, while presenting the forker with the option of whether they want to turn on Actions or not for their fork leaves that decision up to them.
