### ISSUE TITLE
The github actions should not run in private forks

### ISSUE THREAD

**Issue by janhoy** [UCLALibrary/docker-cantaloupe#126]
I forked the repo to create my PR. Turns out that my fork tries to do a release :)
Perhaps make the release tasks only run on the UCLALibrary repo.

**Comment by ksclarke** [comment]
A release? A release should only be done on the merge into the main branch.

Are you talking about the workflows that are waiting as a part of #125? Those should just be regular builds. We have automated builds that happen when a fork is opened. Our process is to see those builds succeed before merging the fork. GitHub has paused those temporarily though, giving us a chance to review them before they happen, since the fork is from outside the org (since that could be a security risk -- e.g., if someone tried to send our ENV secrets to a scraper living on another server). We do want that automated build to happen still, but just after we've had a chance to review it.

Or, are you seeing a build release somewhere else?

**Comment by janhoy** [comment]
This is what I'm seeing in my fork - I got emails about the failed release, so then I checked what was wrong:
![Skjermbilde 2021-11-30 kl  15 24 32](https://user-images.githubusercontent.com/409128/144064997-76418466-63e1-4837-837b-7afe80129b47.png)

**Comment by janhoy** [comment]
Detailed error in the release job - looks like it runs on a schedule!
![Skjermbilde 2021-11-30 kl  15 24 32](https://user-images.githubusercontent.com/409128/144065491-2c074c77-51e5-4927-9b95-65d7ec08eca0.png)

**Comment by janhoy** [comment]
Try to fork your repo and you'll probably see it too.

**Comment by ksclarke** [comment]
Ah, yes, thanks. We do have a snapshot build that runs nightly. I guess it's an unversioned release of sorts. I'll look into how to prevent that from running on the forked repo. You'll still see the failure of the regular build though (and get an email about it, I guess). Not sure if there is a way to prevent that(?)

**Comment by ksclarke** [comment]
I wonder if there is a way to prevent the regular build from showing on the forked repo too(?) I'll have to look into that. Thanks!

**Comment by janhoy** [comment]
I have filtered actions by branch before, I'm sure they can be filtered on repo or other properties as well.

**Comment by ksclarke** [comment]
Corresponding ticket in our Jira: [SERV-306](https://jira.library.ucla.edu/browse/SERV-306)

**Comment by ksclarke** [comment]
Hmm, seems GitHub's solution for this is a little clunky: https://github.community/t/stop-github-actions-running-on-a-fork/17965/2

Either: 1) have the forked repo turn off actions (which pushes the work onto the forker) or 2) set each job in the workflow to filter on the repo it's being run on. Neither of these sounds like the ideal solution to me (which, I guess, would be to have GAs turned off by default on forked repos).

What do you think about this @janhoy? I kind of think it makes more sense to have forkers turn GAs off on the forked repo since a run there doesn't make sense anyway -- I'd say it's the build on the source repo that matters.

**Comment by janhoy** [comment]
Having it done automatically would of course be the best, if that is doable with filters.

However, I disabled actions on my fork (Settings -> Actions -> disable). It's easy so a good first step is to just document it.

**Comment by ksclarke** [comment]
If there is one filter, that seems easy. Having to do it on each step of the build though seems a pain (and that doesn't stop the build itself, just all the steps within it).

I'll keep investigating for a way to have a single "skip this action if" filter, but we may fall back on documenting the path of pushing this work to the forker if a single filter cannot be set up.

**Comment by ksclarke** [comment]
I'm guessing the build failed for your fork too just because it's missing ENV secrets (I think I'd have to fork this myself to confirm). We could alternatively just try to make sure there are defaults for those ENVs that won't cause a failed build.

**Comment by janhoy** [comment]
Is this the filtering solution you found? https://github.community/t/have-github-action-only-run-on-master-repo-and-not-on-forks/140840/18?u=janhoy

**Comment by ksclarke** [comment]
![image](https://user-images.githubusercontent.com/106238/144085873-60b236c6-0609-4288-9f81-4a58e7786624.png)

Oh, when I fork the repo it tells me actions are off by default and I have to explicitly enable them. Did you get this same screen when you first forked?

**Comment by ksclarke** [comment]
![Screenshot from 2021-11-30 11-17-26](https://user-images.githubusercontent.com/106238/144086080-36872bb9-f4a1-4814-a9ff-5573fb508dd6.png)

When I fork, I get this screen on the Actions page telling me they are off by default and that I'd have to turn them on. Did you get this same choice when you first forked?

**Comment by janhoy** [comment]
Hmm, I did another fork today and that one shows the same message. But I used an old fork for the PR, so perhaps that old fork inherited some old settings. 

Guess you can close this as not an issue (for new forks) then. Sorry for the noise.

**Comment by ksclarke** [comment]
No problem at all. I appreciate the feedback.

I can still see someone perhaps wanting to enable local builds but only wanting the regular build one and not the nightly release (which would count against their actions quota). I think I'll add the filter for the nightly snapshot build, still, and not for the regular build. I'll keep this ticket open for that.

**Comment by ksclarke** [comment]
Actually, nevermind... I see in my new fork that, even after I turn on Actions, our two actions also then have to be explicitly and individually turned on because they are scheduled. Even with GAs turned on, the message says:

`This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.`

So now, with the new Action rules, a forker would first have to turn on Actions and then turn on the snapshot build action specifically. So I guess GitHub has addressed this as an issue on their end now. I will go ahead and close this (with the knowledge that if someone has an old fork of the repo they may run into this same issue, but hopefully will find the answer in this ticket thread).
