### ISSUE TITLE
jvm memory alternative for -Xmx

### ISSUE THREAD

**Issue by eduarddrenth** [UCLALibrary/docker-cantaloupe#58]
I've been reading about jvm memory management in containers and it looks like with newer jvm's -Xmx is not anymore the way to go.
I am not confident yet about alternative solutions, but I think it is worth spending some time on this.

**Comment by ksclarke** [comment]
I was just skimming something about this too. I'll have to read up a little more in detail about it, but I like the idea. Thanks.

**Comment by ksclarke** [comment]
When addressing this, we also need to look at `HeapCache.target_size` in the Cantaloupe configs.

**Comment by ksclarke** [comment]
Closing this because our new [5.0.2-0 docker image](https://hub.docker.com/repository/docker/uclalibrary/cantaloupe) uses a heap percentage, now, instead of a fixed size. The default we're using is 80%. This can be overridden by a runtime ENV variable though. The Cantaloupe config still has a fixed value, but that can also be overridden by ENV variables passed to the container at runtime.

**Comment by eduarddrenth** [comment]
great! have it running, lokking good
